### ISSUE TITLE
Column name case sensitivity in postgres

### ISSUE THREAD

**Issue by RayanAhmadani** [slotix/dbconvert-streams-public#29]
We did a successful convert from mysql to postgres, the tables were created and data was loaded, when we switched to CDC mode, we are getting an issue, we have several columns created as upper case in the source MySQL DB, which is nothing we can change or control, now in postgres the columns were created as upper case, no issues, when we did the CDC mode, the columns postgres trying to update are done in lower case, which trigger an error: column does not exist.

for example:
Column in MySQL: CONFIG, converted to Postgres as: CONFIG.
when in CDC
the statement being executed is referring to column config in postgres, which does not exist,

can you help by making the statement being executed uses the same column case as they were created in postgres.

thanks.

**Comment by slotix** [comment]
We've tried to reproduce your case, but it works okay the way you describe. We've checked for both MySQL 8 and the latest version of MariaDB

1. Create MySQL table
```sql
CREATE TABLE IF NOT EXISTS products (
          id BIGINT NOT NULL AUTO_INCREMENT,
          NAME VARCHAR(255) NOT NULL,
          CONFIG VARCHAR(255) NOT NULL,
          price DECIMAL(10, 2) NOT NULL,
          weight DOUBLE NULL,
          created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          PRIMARY KEY (id)
          ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

2. Run DBS services
with the following Stream Config 

```json
{
  "source": {
    "type": "mysql",
    "connection": "root:123456@tcp(0.0.0.0:3306)/source",
    "mode": "cdc",
    "settings": {
      "useDecimal": true,
      "parseTime": true,
      "pingInterval": 10
    },
    "filter": {
      "tables": [
        { "name": "products", "operations": ["insert", "update", "delete"] }
      ]
    }
  },
  "target": {
    "type": "postgresql",
    "connection": "postgres://postgres:postgres@localhost:5433/postgres"
  },
  "limits": {
    "numberOfEvents": 5197
  }
}
```

3. Fill the table with sample data 

```sql
INSERT INTO products (NAME,CONFIG, price, weight)
SELECT
  CONCAT('Product', number) AS NAME,
  CONCAT('Config', number) AS CONFIG,
  ROUND(RAND() * 100, 2) AS price,
  RAND() * 10 AS weight
FROM
  (SELECT @row := @row + 1 AS number FROM
    (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6
     UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) t1,
    (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6
     UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) t2,
    (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6
     UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) t3,
    (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6
     UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) t4,
    (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6
     UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) t5,
   (SELECT @row := 0) r
  ) numbers
LIMIT 10000;
```

## Results:

Source DB

![image](https://github.com/slotix/dbconvert-streams-public/assets/684169/1409e0b1-03e5-44b7-ba69-b41e62bcf3d5)

Target Postgres DB

![image](https://github.com/slotix/dbconvert-streams-public/assets/684169/5add1b08-19a3-4603-bf26-73fd2679a900)
