### ISSUE TITLE
Converting mysql to postgress with column BINARY(16) DEFAULT 0x00 not working

### ISSUE THREAD

**Issue by mstephano** [slotix/dbconvert-streams-public#31]
My MySQL database has a table with a column of type `BINARY(16) NOT NULL DEFAULT 0x00000000000000000000000000000000`.

The error when doing mode convert to postgres is the following:
```sh
target-writer  | [2024/04/27 22:37:58] [error] target/table.go:84 Failed to create table ERROR: trailing junk after numeric literal at or near "0x" (SQLSTATE 42601). DDL: ...
```

Would really appreciate if this can be resolved. Thank you in advance!

**Comment by slotix** [comment]
We've been able to reproduce the case, and it appears that the error stems from the difference in representation of binary data between MySQL and PostgreSQL.

In MySQL, binary literals are indeed commonly represented with a prefix `0x` followed by the hexadecimal values, such as `0x1234567890ABCDEF0000000000000000`.

However, in PostgreSQL, the syntax for representing binary data is different. PostgreSQL uses the `E'\\x'` syntax followed by the hexadecimal values to represent binary data. So, the equivalent representation of `0x1234567890ABCDEF0000000000000000` in PostgreSQL would be `E'\\x1234567890ABCDEF0000000000000000'`.

We are actively working on fixing this bug, and it will be addressed in the next release.

**Comment by slotix** [comment]
fixed in [version 0.10.15 ](https://stream.dbconvert.com/releases-2024#version-0-10-15)

**Comment by slotix** [comment]
Addressed an issue where no default value existed for the BINARY field type.

### Download links

| Operating System | Architecture | Link                                                                                |
| ---------------- | ------------ | ----------------------------------------------------------------------------------- |
| Linux            | AMD64        | [Download](https://dbconvert.com/downloads/dbs/v0.10.16/dbs-v0.10.16-linux-amd64.zip)   |
| Mac OS X         | AMD64        | [Download](https://dbconvert.com/downloads/dbs/v0.10.16/dbs-v0.10.16-darwin-amd64.zip)  |
| Windows          | AMD64        | [Download](https://dbconvert.com/downloads/dbs/v0.10.16/dbs-v0.10.16-windows-amd64.zip) |
| Linux            | ARM64        | [Download](https://dbconvert.com/downloads/dbs/v0.10.16/dbs-v0.10.16-linux-arm64.zip)   |



> I just tested mode cdc on a database that was working fine on v0.10.12, but now have this error on v0.10.15. I am not sure of the table neither the column:
> 
> ```shell
> -- 1-million-records % docker-compose logs -f dbs-target-writer
> target-writer  | DBConvert Streams Target Writer: starting at dbs-target-writer:8022
> target-writer  | Version: v0.10.15  Build time: 2024-04-28_19:14:46
> target-writer  | Find more information at https://stream.dbconvert.com
> target-writer  | [2024/04/29 04:48:08] [info] connected to EventHub. Host: nats:4222
> target-writer  | 2024-04-29 04:48:08.461585881 +0000 UTC m=+2.175248461 write error: nats: no response from stream
> target-writer  | [2024/04/29 04:48:09] [info] subscribed to 'jobs.target'. Ready to receive new streams.
> target-writer  | 2024-04-29 04:48:09.003854714 +0000 UTC m=+2.717516628 write error: nats: no response from stream
> target-writer  | [2024/04/29 04:48:12] [info] dbs-target-writer/main.go:166 received stream configuration. ID: 2flC58THN2BkLt0LwTCMPkXsw8P
> target-writer  | [2024/04/29 04:48:12] [info] target/target.go:80 connected to target database: Type: PostgreSQL | Host: postgres-target | User: postgres | Password: ***** | Database: postgres
> target-writer  | panic: runtime error: slice bounds out of range [2:0]
> target-writer  | 
> target-writer  | goroutine 43 [running]:
> target-writer  | github.com/slotix/dbconvert-stream/internal/dbengine.(*DBEngine).fixPostgresTypes(0xc09600?, 0xc0000a76c0?)
> target-writer  | 	/home/dm3/dbconvert/dbconvert-stream/internal/dbengine/postgres.fixes.go:82 +0x3fb
> target-writer  | github.com/slotix/dbconvert-stream/internal/dbengine.init.func1(0xbb8a20?, 0xc000034c30?)
> target-writer  | 	/home/dm3/dbconvert/dbconvert-stream/internal/dbengine/dbengine.go:38 +0x13
> target-writer  | github.com/slotix/dbconvert-stream/internal/dbengine.(*DBEngine).CreateTableDDL(0xc0001c8d40, {0xdec5c0, 0xc0001008c0}, {0xc00071801a, 0x7})
> target-writer  | 	/home/dm3/dbconvert/dbconvert-stream/internal/dbengine/dbengine.go:360 +0x11e
> target-writer  | github.com/slotix/dbconvert-stream/target.(*Target).CreateTable(0xc0004e8000, {0xdec5c0?, 0xc0001008c0?}, 0xc0005a6900)
> target-writer  | 	/home/dm3/dbconvert/dbconvert-stream/target/table.go:77 +0x54
> target-writer  | github.com/slotix/dbconvert-stream/target.(*Target).ProcessTableStructures(0xc0004e8000, {0xdec5c0, 0xc0001008c0}, 0x1)
> target-writer  | 	/home/dm3/dbconvert/dbconvert-stream/target/table.go:41 +0x38d
> target-writer  | main.(*server).jobsMsgHandler(0xc0000a4f00, {0xdf1f78, 0xc000048760})
> target-writer  | 	/home/dm3/dbconvert/dbconvert-stream/cmd/dbs-target-writer/main.go:205 +0x505
> target-writer  | github.com/nats-io/nats.go/jetstream.(*pullConsumer).Consume.func1(0xc0004a5490)
> target-writer  | 	/home/dm3/go/pkg/mod/github.com/nats-io/nats.go@v1.34.0/jetstream/pull.go:245 +0x2be
> target-writer  | github.com/nats-io/nats%2ego.(*Conn).waitForMsgs(0xc0000dd808, 0xc0004ba0e0)
> target-writer  | 	/home/dm3/go/pkg/mod/github.com/nats-io/nats.go@v1.34.0/nats.go:3106 +0x412
> target-writer  | created by github.com/nats-io/nats%2ego.(*Conn).subscribeLocked in goroutine 1
> target-writer  | 	/home/dm3/go/pkg/mod/github.com/nats-io/nats.go@v1.34.0/nats.go:4320 +0x3a8
> -- 1-million-records % 
> ```

**Comment by mstephano** [comment]
Sorry about the delay, I did not know yesterday about the new release.

So I just tried the new docker image v0.10.16 and I can confirm that the database that was working with v0.10.12 now works properly. Also the database that had the issue with BINARY(16) is also fixed. This is so great, again big thank you for this!
