### ISSUE TITLE
Mode cdc failed on some columns

### ISSUE THREAD

**Issue by mstephano** [slotix/dbconvert-streams-public#36]
Dbconvert version: using docker images v0.10.16

Using mode cdc, I have 3 errors on some columns. I copied my columns in your example file [initdb.sql](https://github.com/slotix/dbconvert-streams-public/blob/main/examples-cdc/mysql2postgres/1-million-records/source/docker-entrypoint-initdb.d/initdb.sql) with the code below, and then I ran your example (no need to insert data, just start the stream with curl):
```sh
CREATE DATABASE `source`;
USE `source`;
CREATE TABLE IF NOT EXISTS `products` (
`id` BIGINT NOT NULL AUTO_INCREMENT,
`col1` point DEFAULT NULL,
`col2` bit(1) NOT NULL DEFAULT b'0',
`col3` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

Here are the 3 errors on each column:
- col1: `source-reader  | [2024/04/30 16:24:28] [error] dbs-source-reader/main.go:240 unknown colType POINT`
- col2: `target-writer    | [2024/04/30 16:32:32] [error] dbs-target-writer/main.go:258 ERROR: column "col2" is of type boolean but default expression is of type bit (SQLSTATE 42804)`
- col3: `target-writer    | [2024/04/30 16:33:38] [error] dbs-target-writer/main.go:258 ERROR: invalid input syntax for type timestamp: "CURRENT_TIMESTAMP(6)" (SQLSTATE 22007)`

Thank you in advanced!

**Comment by slotix** [comment]
Investigating and rectifying the mentioned issues will require some time.

**Comment by slotix** [comment]
@mstephano Find release notes of the latest version at https://stream.dbconvert.com/releases-2024#version-0-11-2 . It addressed all issues listed here.
