### ISSUE TITLE
cdc mode isn't working

### ISSUE THREAD

**Issue by oojikoo** [slotix/dbconvert-streams-public#8]
I followed example [mysql2postgres/10-million-records](https://github.com/slotix/dbconvert-streams-public/tree/main/examples-convert/mysql2postgres/10-million-records)
convert worked as guided.

but when I tried cdc mode
only the first update streamed and no more.

this json I used
```
{
  "source": {
    "type": "mysql",
    "mode": "cdc",
    "connection": "root:123456@tcp(mysql-source:3306)/source",
    "reportingInterval": 5,
    "tables": [
        { "name": "products", "operations": ["insert", "update", "delete"]}
      ]
  },
  "target": {
    "type": "postgresql",
    "connection": "postgres://postgres:postgres@postgres-target:5432/data_db",
    "reportingInterval": 5
  },
  "limits": {
    "numberOfEvents": 1000000,
    "elapsedTime": 0
  }
}

```

this is stat

```
{
  "streamID": "2Ye0fW8gnr5PfniARSoP3kYWEHO",
  "source": {
    "counter": 2,
    "sumDataSize": 0,
    "elapsed": "0s",
    "started": "2023-11-25T00:07:33Z",
    "status": "RUNNING"
  },
  "target": {
    "counter": 1,
    "sumDataSize": 0,
    "elapsed": "0s",
    "started": "2023-11-25T00:07:33Z",
    "status": "RUNNING"
  }
}
```

target counter stayed after the first stream..

**Comment by slotix** [comment]
@oojikoo , could you please check out the example at [CDC example](https://github.com/slotix/dbconvert-streams-public/tree/main/examples/mysql2postgres/1-million-records) ?

Pay attention, especially to step 3. You should start populating the source database right after starting DBConvert Services, as they begin consuming events from the MySQL binlog in runtime.
